### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by fabb**
Activated some warning compiler build settings, and fixed code issues.

There are many usages of `self` within blocks, but as far as I have seen, those are either 
1. only contained within animation blocks, or 
2. in the case of `_pendingCompletionHandler` containing a block that retains `self`, it will be dispatched to be released immediately afterwards

So these `self` retains should be safe? Or should `__weak` rather be used, what do you think?

### CODE REVIEW

**Comment by LeoNatan** [comment]
I don't see the point of this. I especially do not like the need for explicit `self->` requirement. All blocks in this library are temporary and disposed of correctly, so the possibility of a retain cycle falls only on bad practice by the developer, not the library internally. I will not accept the PR. But thanks for submitting.

**Comment by fabb** [comment]
No hard feelings. The explicit use of self-> makes programming mistakes less likely. But as you said, all used in the current version are currently safe.

**Comment by LeoNatan** [comment]
Just a warning. If you have a ```weak``` object, calling ```weakObject->ivar``` will crash if ```weakObject``` is ```nil```. Make sure to take a strong reference to the object and check for nullity.

**Comment by fabb** [comment]
Thanks for the tip. I usually refrain from using ivars directly.

**Pull request closed without merging**
